(function () {
  const q = (key, title, options, body = "") => ({
    key,
    title,
    body,
    type: "options",
    options,
  });

  const m = (key, title, options, body = "") => ({
    key,
    title,
    body,
    type: "multi",
    options,
  });

  const t = (key, title, placeholder = "", body = "") => ({
    key,
    title,
    body,
    type: "text",
    placeholder,
  });

  const a = (key, title, placeholder = "", body = "") => ({
    key,
    title,
    body,
    type: "textarea",
    placeholder,
  });

  const uploads = (body = "") => ({
    ...q("Upload disponibili", "Hai foto o documenti utili?", ["Sì", "No"], body || "Se hai foto, planimetrie o documenti, potrai allegarli dopo in chat WhatsApp o email."),
    optional: true,
  });

  const commonWhere = q("Luogo intervento", "Dove va fatto l'intervento?", [
    "Casa o appartamento",
    "Villa o casa indipendente",
    "B&B",
    "Negozio",
    "Ufficio",
    "Garage/cantina",
    "Esterno",
    "Altro",
  ]);

  const commonUrgency = q("Urgenza", "Quanto è urgente?", [
    "Emergenza",
    "Entro 24 ore",
    "Entro pochi giorni",
    "Entro 1 mese",
    "Solo valutazione",
    "Non so",
  ]);

  const propertyType = q("Tipo immobile", "Che tipo di immobile è?", [
    "Appartamento",
    "Casa indipendente",
    "Villa",
    "Garage/cantina",
    "B&B",
    "Negozio",
    "Ufficio",
    "Capannone",
    "Altro",
  ]);

  const areaSize = q("Superficie", "Superficie indicativa", [
    "Meno di 50 mq",
    "50-80 mq",
    "80-120 mq",
    "120-180 mq",
    "180-400 mq",
    "Oltre 400 mq",
    "Non so",
  ]);

  const powerSupply = q("Fornitura", "Che fornitura elettrica hai o prevedi?", [
    "3 kW",
    "4,5 kW",
    "6 kW",
    "Trifase",
    "Generatore",
    "Non so",
  ]);

  const documents = q("Documentazione", "Che documentazione ti serve?", [
    "DICO",
    "Schema impianto",
    "Relazione materiali",
    "Report fotografico",
    "Solo preventivo",
    "Non so",
  ]);

  const branches = {
    nuova_installazione: {
      label: "Nuova installazione",
      body: "Impianto o sistema nuovo da progettare e realizzare.",
      subcategories: {
        elettrico_casa: {
          label: "Impianto elettrico casa/appartamento",
          outcome: "Sopralluogo consigliato",
          questions: [
            propertyType,
            areaSize,
            q("Numero piani", "Numero piani", ["1", "2", "3", "Oltre 3"]),
            q("Stato immobile", "Stato dell'immobile", [
              "Nuova costruzione",
              "Ristrutturazione",
              "Casa abitata",
              "Casa vuota",
              "Impianto vecchio da rifare",
              "Sto solo valutando",
            ]),
            m("Ambienti", "Quali ambienti sono presenti?", [
              "Cucina",
              "Soggiorno",
              "Camere",
              "Bagni",
              "Corridoi",
              "Garage",
              "Cantina",
              "Esterno/giardino",
              "Locale tecnico",
              "Terrazzo/balcone",
            ]),
            m("Predisposizioni", "Predisposizioni future", [
              "Fotovoltaico",
              "Wallbox",
              "Domotica",
              "Allarme",
              "Videosorveglianza",
              "Wi-Fi/rete dati",
              "Climatizzazione",
              "Cancello",
              "Piscina/giardino",
            ]),
            powerSupply,
            documents,
            uploads("Planimetria, foto quadro, contatore, locali o lavori in corso."),
          ],
        },
        attivita: {
          label: "Impianto per B&B, negozio o ufficio",
          outcome: "Sopralluogo consigliato",
          questions: [
            q("Tipo attivita", "Tipo attività", [
              "B&B",
              "Negozio",
              "Ufficio",
              "Studio professionale",
              "Bar/ristorazione",
              "Magazzino",
              "Laboratorio",
              "Altro",
            ]),
            q("Superficie", "Superficie indicativa", [
              "Meno di 50 mq",
              "50-100 mq",
              "100-200 mq",
              "Oltre 200 mq",
            ]),
            t("Numero locali", "Numero locali o stanze", "Es. 4 stanze + reception"),
            m("Servizi richiesti", "Cosa ti serve?", [
              "Impianto elettrico",
              "Prese/postazioni",
              "Quadro",
              "Illuminazione",
              "Luci emergenza",
              "Wi-Fi ospiti",
              "Rete dati",
              "Videosorveglianza",
              "Controllo consumi",
              "Smart home",
              "Manutenzione",
              "DICO/documenti",
            ]),
            q("Documenti disponibili", "Documenti impianto", [
              "Ho DICO",
              "Non ho DICO",
              "Non so",
              "Devo aprire attività",
              "Devo affittare",
              "Devo regolarizzare",
            ]),
            uploads("Foto quadro, contatore, planimetria, locali o documenti impianto."),
          ],
        },
        quadro_nuovo: {
          label: "Quadro elettrico nuovo",
          outcome: "Sopralluogo consigliato",
          questions: [
            q("Tipo quadro", "Che tipo di quadro serve?", [
              "Appartamento",
              "Generale casa",
              "Garage/cantina",
              "Esterno",
              "Negozio/ufficio",
              "Trifase",
              "Piscina/giardino",
              "Evento/cantiere",
              "Non so",
            ]),
            powerSupply,
            m("Linee da proteggere", "Linee da separare o proteggere", [
              "Luci",
              "Prese",
              "Cucina",
              "Forno",
              "Piano induzione",
              "Lavatrice",
              "Asciugatrice",
              "Climatizzatori",
              "Garage",
              "Esterno",
              "Pompa",
              "Fotovoltaico",
              "Wallbox",
              "Allarme",
              "Rete/server",
              "Piscina",
            ]),
            m("Predisposizioni future", "Predisposizioni future", [
              "Fotovoltaico",
              "Wallbox",
              "Domotica",
              "Piscina",
              "Giardino",
              "Rete dati",
              "Nessuna",
              "Non so",
            ]),
            documents,
            uploads("Foto contatore, zona installazione, quadro esistente e percorso cavi."),
          ],
        },
        smart_home: {
          label: "Smart home/domotica",
          outcome: "Consulenza smart home",
          questions: [
            m("Cosa automatizzare", "Cosa vuoi automatizzare?", [
              "Luci",
              "Tapparelle",
              "Prese",
              "Riscaldamento",
              "Climatizzazione",
              "Consumi",
              "Sensori allagamento",
              "Sensori movimento",
              "Porte/finestre",
              "Cancello",
              "Irrigazione",
              "Videocitofono",
              "Tutta la casa",
            ]),
            q("Sistema desiderato", "Sistema desiderato", [
              "Home Assistant",
              "Shelly",
              "Zigbee",
              "Wi-Fi",
              "BTicino/Legrand",
              "KNX",
              "Non so",
            ]),
            t("Quantita dispositivi", "Quanti dispositivi o stanze?", "Es. 7 tapparelle, 12 luci, 4 stanze"),
            q("Stato impianto", "Stato impianto", [
              "Casa abitata",
              "Ristrutturazione",
              "Impianto nuovo",
              "Impianto vecchio",
              "Gia smart in parte",
            ]),
            q("Neutro scatole", "Neutro nelle scatole comandi", ["Sì", "No", "Non so"]),
            m("Servizio richiesto", "Servizio richiesto", [
              "Consulenza",
              "Progetto",
              "Fornitura dispositivi",
              "Installazione",
              "Configurazione app",
              "Home Assistant",
              "Assistenza remota",
              "Tutto completo",
            ]),
            uploads("Foto quadro, interruttori, scatole comandi, dispositivi, planimetria."),
          ],
        },
        rete_wifi: {
          label: "Wi-Fi/rete dati",
          outcome: "Progetto rete",
          questions: [
            propertyType,
            areaSize,
            q("Piani", "Numero piani", ["1", "2", "3", "Oltre 3"]),
            m("Obiettivo problema", "Obiettivo o problema", [
              "Nuova rete",
              "Wi-Fi debole",
              "Zone senza segnale",
              "Connessione instabile",
              "Troppi dispositivi",
              "Rete ospiti",
              "Rete B&B",
              "Rete telecamere",
              "Rete smart home",
              "Rete cablata",
            ]),
            q("Dispositivi collegati", "Dispositivi collegati", [
              "1-10",
              "10-30",
              "30-60",
              "Oltre 60",
            ]),
            q("Punti rete", "Punti rete cablati", [
              "Nessuno",
              "1-3",
              "4-6",
              "7-12",
              "Oltre 12",
            ]),
            m("Ostacoli", "Muri o ostacoli", [
              "Normali",
              "Cemento armato",
              "Pietra",
              "Muri spessi",
              "Piu piani",
              "Giardino/esterno",
              "Non so",
            ]),
            m("Apparecchi esistenti", "Apparecchi esistenti", [
              "Modem operatore",
              "Router",
              "Mesh",
              "Access point",
              "Rack",
              "Nessuno",
              "Non so",
            ]),
            uploads("Planimetria, posizione modem, foto locali, rack o prese dati."),
          ],
        },
        videosorveglianza: {
          label: "Videosorveglianza",
          outcome: "Preventivo kit + installazione",
          questions: [
            commonWhere,
            q("Numero telecamere", "Numero telecamere", ["1-2", "3-4", "5-8", "Oltre 8"]),
            m("Zone da coprire", "Zone da coprire", [
              "Ingresso",
              "Cancello",
              "Giardino",
              "Garage",
              "Parcheggio",
              "Interno",
              "Magazzino",
              "Cassa/bancone",
              "Corridoi",
              "Altro",
            ]),
            q("Tecnologia", "Tecnologia preferita", ["Wi-Fi", "Cablate", "PoE", "Non so"]),
            q("Predisposizioni", "Ci sono predisposizioni?", ["Sì", "No", "In parte", "Non so"]),
            q("Registrazione", "Tipo registrazione", [
              "Solo live",
              "Continua",
              "Movimento",
              "Cloud",
              "NVR locale",
              "Non so",
            ]),
            q("App telefono", "Vuoi controllo da app?", [
              "Sì",
              "No",
              "Sì con notifiche",
              "Sì con più utenti",
              "Non so",
            ]),
            uploads("Foto zone da coprire, modem/router, quadro, planimetria."),
          ],
        },
        videocitofono: {
          label: "Videocitofono/controllo accessi",
          outcome: "Verifica predisposizione",
          questions: [
            m("Cosa serve", "Cosa serve?", [
              "Videocitofono nuovo",
              "Sostituzione citofono",
              "Apertura cancello",
              "Apertura porta",
              "Tastierino/codici",
              "Lettore badge",
              "App smartphone",
            ]),
            commonWhere,
            q("Impianto esistente", "Impianto esistente", ["Citofono", "Videocitofono", "No", "Non so"]),
            q("Distanza", "Distanza posto esterno/interno", [
              "Meno di 10 m",
              "10-30 m",
              "Oltre 30 m",
              "Non so",
            ]),
            q("Smartphone", "Apertura da smartphone", ["Sì", "No", "Non so"]),
            uploads("Vecchio citofono, cancello/porta, quadro, percorso cavi."),
          ],
        },
        fotovoltaico: {
          label: "Fotovoltaico/monitoraggio consumi",
          outcome: "Analisi tecnica",
          questions: [
            q("Cosa fare", "Cosa vuoi fare?", [
              "Nuovo fotovoltaico",
              "Batteria accumulo",
              "Monitoraggio consumi",
              "Predisposizione futura",
              "Non so",
            ]),
            commonWhere,
            q("Consumo annuo", "Consumo annuo indicativo", [
              "Meno di 2.000 kWh",
              "2.000-4.000 kWh",
              "4.000-6.000 kWh",
              "Oltre 6.000 kWh",
              "Non so",
            ]),
            q("Potenza desiderata", "Potenza desiderata", [
              "3 kW",
              "4,5 kW",
              "6 kW",
              "10 kW",
              "Oltre 10 kW",
              "Non so",
            ]),
            q("Tetto", "Tipo tetto o installazione", [
              "Falda coppi/tegole",
              "Piano",
              "Lamiera",
              "Guaina",
              "Cemento",
              "Pergola",
              "Terreno",
              "Non so",
            ]),
            q("Orientamento", "Orientamento", ["Sud", "Est", "Ovest", "Est/Ovest", "Nord", "Piu falde", "Non so"]),
            m("Ombre", "Ci sono ombre?", ["Nessuna", "Camino", "Alberi", "Palazzi", "Antenne", "Altre ombre", "Non so"]),
            powerSupply,
            q("Accumulo", "Accumulo", ["Sì", "No", "Forse", "Predisposizione"]),
            uploads("Bolletta, foto tetto, quadro, contatore, planimetria o screenshot mappa."),
          ],
        },
        gazebo_evento: {
          label: "Gazebo/evento temporaneo",
          outcome: "Kit o verifica in loco",
          questions: [
            q("Tipo evento", "Tipo evento", [
              "Festa privata",
              "Gazebo giardino",
              "DJ/audio/luci",
              "Banco bar/frigo/spillatore",
              "Stand/mercatino",
              "Food truck/cucina",
              "Aziendale",
              "Aperto al pubblico",
            ]),
            q("Luogo", "Luogo", [
              "Interno",
              "Esterno coperto",
              "Esterno scoperto",
              "Giardino",
              "Gazebo",
              "Piazza/area pubblica",
              "Locale commerciale",
              "Non so",
            ]),
            m("Carichi", "Cosa devi alimentare?", [
              "Luci decorative",
              "Casse audio",
              "Console DJ",
              "Frigo",
              "Spillatore",
              "Macchina ghiaccio",
              "Banco bar",
              "Forno",
              "Friggitrice",
              "Piastra",
              "Pompa",
              "Stand",
              "Caricabatterie",
              "Altro",
            ]),
            q("Numero prese", "Numero prese", ["1-3", "4-6", "7-10", "Oltre 10"]),
            q("Zone separate", "Zone separate", ["1", "2", "3", "4 o più"]),
            powerSupply,
            q("Distanza alimentazione", "Distanza alimentazione/zona evento", [
              "Meno di 5 m",
              "5-10 m",
              "10-20 m",
              "20-30 m",
              "Oltre 30 m",
            ]),
            q("Passaggio cavi", "Passaggio cavi", ["No", "Persone", "Auto", "Non so"]),
            m("Servizio richiesto", "Servizio richiesto", [
              "Consulenza evento",
              "Preventivo kit",
              "Check remoto",
              "Installazione Eletwave",
              "Verifica in loco con eventuale DICO",
              "Allestimento completo",
            ]),
            uploads("Area evento, gazebo, punto alimentazione, quadro, presa, attrezzature."),
          ],
        },
      },
    },
    assistenza: {
      label: "Assistenza tecnica / riparazione",
      body: "Guasto, problema o sistema esistente da sistemare.",
      subcategories: {
        impianto: {
          label: "Impianto elettrico",
          outcome: "Intervento tecnico",
          questions: [
            m("Problema", "Che problema hai?", [
              "Non arriva corrente",
              "Presa non funziona",
              "Luce non funziona",
              "Interruttore non funziona",
              "Contatore salta",
              "Odore di bruciato",
              "Scintille",
              "Rumori strani",
              "Altro",
            ]),
            q("Quando succede", "Quando succede?", [
              "Sempre",
              "Ogni tanto",
              "Quando accendo un apparecchio",
              "Quando piove",
              "Di notte",
              "Non so",
            ]),
            q("Da quanto", "Da quanto tempo?", ["Da oggi", "Pochi giorni", "Settimane", "Mesi", "Non so"]),
            commonUrgency,
            commonWhere,
            uploads("Foto quadro, video problema, apparecchio coinvolto, presa/interruttore."),
          ],
        },
        quadro_salvavita: {
          label: "Quadro/salvavita",
          outcome: "Verifica quadro",
          questions: [
            m("Problema", "Cosa succede?", [
              "Salvavita scatta",
              "Contatore salta",
              "Magnetotermico scatta",
              "Quadro caldo",
              "Odore di bruciato",
              "Scintille",
              "Quadro vecchio",
              "Non so quale interruttore scatta",
            ]),
            q("Succede accendendo qualcosa", "Succede quando accendi qualcosa?", ["Sì", "No", "A volte", "Non so"]),
            q("Succede quando piove", "Succede quando piove?", ["Sì", "No", "Non so"]),
            powerSupply,
            q("Tipo quadro", "Tipo quadro", ["Piccolo appartamento", "Generale casa", "Negozio/ufficio", "Trifase", "Non so"]),
            uploads("Quadro chiuso, quadro aperto se sicuro, contatore, interruttore che scatta."),
          ],
        },
        prese_luci: {
          label: "Prese o luci",
          outcome: "Intervento semplice o verifica linea",
          questions: [
            m("Problema", "Che problema hai?", [
              "Presa non funziona",
              "Luce non accende",
              "Lampada lampeggia",
              "Interruttore non funziona",
              "Presa scalda",
              "Presa bruciata",
              "Differenziale scatta usando quella presa",
              "Altro",
            ]),
            q("Punti coinvolti", "Quanti punti sono coinvolti?", ["1", "2-3", "4-6", "Oltre 6"]),
            m("Dove", "Dove si trovano?", ["Cucina", "Soggiorno", "Camera", "Bagno", "Corridoio", "Garage", "Esterno", "Negozio/ufficio", "Altro"]),
            q("Da quanto", "Da quanto tempo?", ["Oggi", "Pochi giorni", "Settimane", "Mesi"]),
            uploads("Foto presa/lampada, interruttore, quadro o video problema."),
          ],
        },
        smart_assistenza: {
          label: "Smart home/domotica",
          outcome: "Assistenza remota possibile",
          questions: [
            m("Cosa non funziona", "Cosa non funziona?", [
              "Luci smart",
              "Tapparelle smart",
              "Prese smart",
              "Sensori",
              "Home Assistant",
              "Zigbee",
              "App",
              "Automazioni",
              "Misuratore consumi",
              "Altro",
            ]),
            q("Sistema", "Sistema", ["Shelly", "Home Assistant", "Zigbee", "Wi-Fi", "BTicino/Legrand", "KNX", "Altro", "Non so"]),
            q("Tipo problema", "Tipo problema", ["Configurazione app", "Dispositivo offline", "Problema elettrico", "Automazione sbagliata", "Rete Wi-Fi", "Non so"]),
            q("Dispositivi coinvolti", "Dispositivi coinvolti", ["1", "2-5", "6-10", "Oltre 10"]),
            q("Accesso remoto", "Accesso remoto possibile?", ["Sì", "No", "Non so"]),
            uploads("Screenshot app, dispositivo, quadro, scatola comando, errore Home Assistant."),
          ],
        },
        wifi_assistenza: {
          label: "Wi-Fi/rete dati",
          outcome: "Consulenza Wi-Fi",
          questions: [
            m("Problema", "Che problema hai?", ["Wi-Fi lento", "Wi-Fi assente", "Zone senza segnale", "Rete cade", "Dispositivi non si collegano", "Telecamere offline", "Smart home offline", "Rete ospiti", "Altro"]),
            propertyType,
            areaSize,
            q("Piani", "Piani", ["1", "2", "3", "Oltre 3"]),
            q("Dispositivi collegati", "Dispositivi collegati", ["1-10", "10-30", "30-60", "Oltre 60"]),
            t("Provider internet", "Provider internet", "Es. TIM, Vodafone, Iliad..."),
            m("Apparecchi", "Apparecchi presenti", ["Modem", "Router", "Mesh", "Access point", "Switch", "Rack", "Non so"]),
            uploads("Planimetria, modem/router, speed test, access point/switch, zone senza segnale."),
          ],
        },
        videosorveglianza_assistenza: {
          label: "Videosorveglianza",
          outcome: "Assistenza remota possibile",
          questions: [
            m("Problema", "Che problema hai?", ["Telecamera offline", "Non registra", "App non funziona", "Immagini disturbate", "Notifiche non arrivano", "NVR non funziona", "Telecamera non alimentata", "Altro"]),
            q("Dispositivi coinvolti", "Dispositivi coinvolti", ["1", "2-3", "4-8", "Oltre 8"]),
            q("Tecnologia", "Tecnologia", ["Wi-Fi", "Cablate", "PoE", "Non so"]),
            t("Marca modello", "Marca/modello se lo conosci", "Es. Hikvision, Dahua, Reolink..."),
            q("Da quando", "Da quando succede?", ["Oggi", "Pochi giorni", "Dopo cambio modem", "Dopo blackout", "Da sempre", "Non so"]),
            uploads("Screenshot app, telecamera, NVR, modem/router, alimentatore/switch PoE."),
          ],
        },
        videocitofono_assistenza: {
          label: "Videocitofono",
          outcome: "Assistenza videocitofono",
          questions: [
            m("Problema", "Che problema hai?", ["Non suona", "Non si vede video", "Non apre cancello/porta", "Audio non funziona", "App non funziona", "Pulsante non funziona", "Altro"]),
            q("Tipo impianto", "Tipo impianto", ["Citofono", "Videocitofono", "Smart/app", "Non so"]),
            commonWhere,
            uploads("Posto interno, posto esterno, screenshot app, alimentatore/quadro."),
          ],
        },
        fv_assistenza: {
          label: "Fotovoltaico/monitoraggio",
          outcome: "Assistenza monitoraggio",
          questions: [
            m("Problema", "Che problema hai?", ["App non funziona", "Monitoraggio offline", "Produzione bassa", "Inverter in errore", "Batteria non carica", "Consumi non corretti", "Altro"]),
            t("Marca inverter", "Marca inverter", "Es. Huawei, Fronius, SMA..."),
            q("Potenza impianto", "Potenza impianto", ["3 kW", "4,5 kW", "6 kW", "Oltre 6 kW", "Non so"]),
            q("Batteria", "Hai batteria?", ["Sì", "No", "Non so"]),
            t("Codice errore", "Codice errore se presente", "Es. codice visto su inverter o app"),
            uploads("Screenshot app, inverter, batteria, quadro, contatore."),
          ],
        },
      },
    },
    modifica: {
      label: "Modifica o ampliamento impianto",
      body: "Aggiunta di punti, linee, quadro, smart home o rete dati.",
      subcategories: {
        prese: {
          label: "Prese",
          outcome: "Preventivo indicativo online",
          questions: [
            q("Quante prese", "Quante prese?", ["1", "2-3", "4-6", "7-10", "Oltre 10"]),
            m("Dove", "Dove servono?", ["Cucina", "Soggiorno", "Camera", "Bagno", "Garage", "Esterno", "Negozio/ufficio", "Altro"]),
            q("Tipo posa", "Tipo posa", ["Incasso", "Canalina", "Cartongesso", "Tubazione esistente", "Non so"]),
            q("Stato ambiente", "Stato ambiente", ["Casa abitata", "Muri finiti", "Lavori in corso", "Tracce già fatte", "Non so"]),
            q("Serie civile", "Serie civile", ["Uguale all'esistente", "Base", "Standard", "Premium", "Smart", "Non so"]),
            uploads("Punto intervento, presa esistente, quadro, planimetria semplice."),
          ],
        },
        punti_luce: {
          label: "Punti luce",
          outcome: "Preventivo indicativo online",
          questions: [
            q("Quanti punti luce", "Quanti punti luce?", ["1", "2-3", "4-6", "7-10", "Oltre 10"]),
            m("Tipo luce", "Tipo luce", ["Lampadario", "Plafoniera", "Faretti", "LED strip", "Applique", "Esterno", "Altro"]),
            q("Alimentazione esistente", "Alimentazione esistente?", ["Sì", "No", "Non so"]),
            q("Comando", "Tipo comando", ["Interruttore", "Deviatore", "Dimmer", "Sensore movimento", "Crepuscolare", "Smart/app", "Non so"]),
            uploads("Punto luce, soffitto/parete, interruttore, quadro."),
          ],
        },
        linea_dedicata: {
          label: "Linea dedicata",
          outcome: "Verifica quadro necessaria",
          questions: [
            q("Apparecchio", "Per quale apparecchio?", ["Forno", "Piano induzione", "Lavatrice", "Asciugatrice", "Climatizzatore", "Pompa", "Garage", "Cancello", "Wallbox", "Fotovoltaico", "Server/rete", "Piscina", "Gazebo/esterno", "Altro"]),
            q("Potenza apparecchio", "Potenza apparecchio", ["Meno di 1 kW", "1-2 kW", "2-3 kW", "Oltre 3 kW", "Non so"]),
            q("Distanza quadro", "Distanza dal quadro", ["Meno di 5 m", "5-10 m", "10-20 m", "Oltre 20 m", "Non so"]),
            q("Tipo posa", "Tipo posa", ["Incasso", "Canalina", "Tubazione esistente", "Esterno", "Interrato", "Non so"]),
            uploads("Quadro, percorso, apparecchio, punto arrivo."),
          ],
        },
        quadro_modifica: {
          label: "Quadro elettrico",
          outcome: "Sopralluogo tecnico",
          questions: [
            m("Cosa fare", "Cosa bisogna fare?", ["Aggiungere spazio", "Separare linee", "Aggiungere differenziale", "Aggiungere protezioni", "Predisporre FV", "Predisporre wallbox", "Predisporre domotica", "Sistemare quadro"]),
            uploads("Foto quadro e contatore."),
          ],
        },
        smart_modifica: {
          label: "Smart home",
          outcome: "Consulenza smart",
          questions: [
            m("Cosa aggiungere", "Cosa vuoi aggiungere?", ["Luci smart", "Tapparelle smart", "Prese smart", "Sensori", "Controllo consumi", "Home Assistant", "Altro"]),
            t("Quantita", "Quantità dispositivi", "Es. 4 tapparelle, 6 luci"),
            t("Sistema esistente", "Sistema esistente", "Es. Shelly, Home Assistant, BTicino..."),
            uploads("Foto e screenshot utili."),
          ],
        },
        rete_modifica: {
          label: "Rete dati/Wi-Fi",
          outcome: "Progetto Wi-Fi",
          questions: [
            m("Cosa aggiungere", "Cosa vuoi aggiungere?", ["Punto rete", "Access point", "Rack", "Switch", "Rete ospiti", "Copertura esterna"]),
            t("Quantita", "Quantità", "Es. 3 punti rete, 2 access point"),
            uploads("Planimetria, modem/router, locali, rack, prese dati."),
          ],
        },
      },
    },
    verifica: {
      label: "Verifica, manutenzione o DICO",
      body: "Controlli, documenti, report tecnico e manutenzioni.",
      subcategories: {
        controllo_sicurezza: {
          label: "Controllo sicurezza impianto",
          outcome: "Check sicurezza",
          questions: [
            propertyType,
            q("Eta impianto", "Eta impianto", ["Meno di 5 anni", "5-10 anni", "10-20 anni", "Oltre 20 anni", "Non so"]),
            q("DICO presente", "DICO presente?", ["Sì", "No", "Non so"]),
            m("Problemi", "Problemi presenti", ["Salvavita scatta", "Contatore salta", "Prese vecchie", "Quadro vecchio", "Nessun problema", "Altro"]),
            q("Report scritto", "Vuoi report scritto?", ["Sì", "No", "Non so"]),
            uploads("Quadro, contatore, prese, documenti impianto."),
          ],
        },
        manutenzione: {
          label: "Manutenzione periodica",
          outcome: "Piano manutenzione",
          questions: [
            q("Tipo cliente", "Tipo cliente", ["Privato", "B&B", "Negozio", "Ufficio", "Condominio", "Altro"]),
            m("Cosa controllare", "Cosa controllare?", ["Quadro", "Differenziali", "Luci emergenza", "Prese", "Wi-Fi", "Videosorveglianza", "Fotovoltaico", "Smart home", "Tutto"]),
            q("Frequenza", "Frequenza", ["Una volta", "Annuale", "Semestrale", "Trimestrale", "Non so"]),
          ],
        },
        dico: {
          label: "DICO/documenti impianto",
          outcome: "Check documenti DICO",
          questions: [
            q("Cosa serve", "Cosa serve?", ["Mi serve DICO", "Controllo DICO ricevuta", "Mancano allegati", "Impianto senza documenti", "Lavori con altra impresa", "Lavori fai da te", "Non so"]),
            q("Chi ha fatto lavori", "Chi ha fatto i lavori?", ["Eletwave", "Altra impresa", "Fai da te", "Vecchio proprietario", "Non so"]),
            m("Documenti disponibili", "Documenti disponibili", ["DICO", "Schema", "Relazione materiali", "Fatture", "Foto lavori", "Certificati componenti", "Nessuno"]),
            m("Servizio", "Servizio richiesto", ["Check documenti online", "Elenco mancanti", "Consulenza documentale", "Sopralluogo", "Adeguamento impianto", "DICO per lavori Eletwave"]),
            uploads("DICO, allegati, quadro, impianto, preventivi/fatture, comunicazioni."),
          ],
        },
        vendita_affitto: {
          label: "Verifica per vendita/affitto/apertura attività",
          outcome: "Check documentale",
          questions: [
            q("Finalita", "Finalita", ["Vendere casa", "Affittare casa", "Aprire B&B", "Aprire negozio", "Aprire ufficio", "Regolarizzare impianto"]),
            q("Chi richiede documenti", "Chi richiede i documenti?", ["Agenzia immobiliare", "Comune", "Tecnico/geometra", "Proprietario", "Non so"]),
            m("Documenti disponibili", "Documenti disponibili", ["DICO", "Planimetria", "Visura/catasto", "Nessun documento", "Non so"]),
          ],
        },
        report: {
          label: "Report tecnico",
          outcome: "Report tecnico",
          questions: [
            q("Tipo report", "Tipo report", ["Stato impianto", "Criticita", "Documenti mancanti", "Preventivo adeguamento", "Altro"]),
            uploads("Foto, documenti, preventivi, planimetria."),
          ],
        },
      },
    },
    consulenza: {
      label: "Consulenza online / preventivo",
      body: "Secondo parere, analisi preventivi, documenti o progetto preliminare.",
      subcategories: {
        secondo_parere: {
          label: "Secondo parere tecnico",
          outcome: "Consulenza online",
          questions: [a("Descrizione problema", "Descrivi il problema"), a("Soluzione proposta", "Che soluzione ti hanno proposto?"), q("Preventivo Eletwave", "Vuoi anche un preventivo Eletwave?", ["Sì", "No", "Non so"]), uploads("Foto, video o documenti.")],
        },
        analisi_preventivo: {
          label: "Analisi preventivo ricevuto",
          outcome: "Analisi preventivo online",
          questions: [
            q("Tipo preventivo", "Tipo preventivo", ["Impianto elettrico", "Smart home", "Fotovoltaico", "Wi-Fi/rete", "Videosorveglianza", "Gazebo/evento", "Altro"]),
            m("Cosa capire", "Cosa vuoi capire?", ["Prezzo", "Materiali", "Mancanze", "Sicurezza", "Alternative", "Convenienza"]),
            uploads("Preventivo, schede tecniche, foto impianto, note cliente."),
          ],
        },
        check_dico: {
          label: "Check documenti DICO",
          outcome: "Consulenza documentale",
          questions: [
            m("Documenti caricati", "Documenti che puoi inviare", ["DICO", "Allegati obbligatori", "Schema", "Relazione materiali", "Fattura", "Altro"]),
            q("Motivo controllo", "Motivo controllo", ["Vendita", "Affitto", "Lavori appena fatti", "Dubbi su impresa", "Apertura attività", "Altro"]),
            uploads("Documenti e allegati."),
          ],
        },
        smart_consulenza: {
          label: "Consulenza smart home",
          outcome: "Progetto smart home",
          questions: [m("Cosa fare", "Cosa vuoi fare?", ["Luci", "Tapparelle", "Home Assistant", "Sensori", "Consumi", "Automazioni"]), t("Quantita e sistema", "Quantità dispositivi e sistema attuale", "Es. 8 luci, Shelly, app..."), uploads("Foto o screenshot.")],
        },
        wifi_consulenza: {
          label: "Consulenza Wi-Fi",
          outcome: "Progetto Wi-Fi",
          questions: [areaSize, q("Piani", "Piani", ["1", "2", "3", "Oltre 3"]), m("Problema", "Problema", ["Wi-Fi debole", "Zone senza segnale", "Troppi dispositivi", "Rete ospiti", "Rete telecamere"]), q("Dispositivi", "Dispositivi", ["1-10", "10-30", "30-60", "Oltre 60"]), uploads("Planimetria e foto modem/router.")],
        },
        fv_consulenza: {
          label: "Consulenza fotovoltaico",
          outcome: "Analisi FV",
          questions: [q("Materiale disponibile", "Cosa puoi inviare?", ["Bolletta", "Preventivo ricevuto", "Foto tetto", "kW proposti", "Tutto", "Non so"]), t("kW proposti", "kW proposti o desiderati", "Es. 6 kW + batteria"), uploads("Bolletta, preventivo, foto tetto.")],
        },
        evento_consulenza: {
          label: "Consulenza gazebo/eventi",
          outcome: "Consulenza evento",
          questions: [q("Tipo evento", "Tipo evento", ["Privato", "Aziendale", "Pubblico", "Food/bar", "DJ/audio/luci"]), m("Carichi", "Carichi", ["Luci", "Audio", "Frigo", "Spillatore", "Forno", "Friggitrice", "Altro"]), powerSupply, uploads("Foto area e punto alimentazione.")],
        },
        ristrutturazione: {
          label: "Consulenza ristrutturazione casa",
          outcome: "Schema preliminare",
          questions: [areaSize, t("Stanze", "Stanze e ambienti", "Es. cucina, sala, 2 camere, 2 bagni"), m("Richieste", "Cosa vuoi prevedere?", ["Prese", "Luci", "Rete dati", "Domotica", "Allarme", "Videosorveglianza", "Wallbox", "Fotovoltaico"]), uploads("Planimetria o foto.")],
        },
      },
    },
    kit: {
      label: "Kit predisposti / soluzioni pronte",
      body: "Soluzioni pronte o semi-pronte, configurate da Eletwave.",
      subcategories: {
        stand: {
          label: "Kit fiere/stand/mercatini",
          outcome: "Kit predisposto consigliato",
          questions: [
            q("Tipo utilizzo", "Tipo utilizzo", ["Stand espositivo", "Mercatino", "Fiera", "Banco vendita", "Informativo", "Artigianato", "Food leggero"]),
            q("Luogo", "Luogo", ["Interno", "Esterno coperto", "Esterno scoperto", "Area pubblica", "Padiglione fiera"]),
            m("Cosa alimentare", "Cosa alimentare?", ["Luci stand", "POS", "Tablet/PC", "Piccoli apparecchi", "Frigo", "Insegna", "Caricabatterie", "Altro"]),
            q("Numero prese", "Numero prese", ["1-3", "4-6", "7-10", "Oltre 10"]),
            powerSupply,
            q("Passaggi cavi", "Passaggi cavi", ["Passaggio persone", "Passaggio auto", "Nessun passaggio", "Non so"]),
            q("Servizio", "Servizio", ["Kit pronto", "Kit + check remoto", "Kit + installazione", "Verifica in loco/DICO se applicabile"]),
            uploads("Area stand, presa/quadro disponibile, lista attrezzature, planimetria."),
          ],
        },
        gazebo_kit: {
          label: "Kit gazebo/feste/eventi",
          outcome: "Kit predisposto consigliato",
          questions: [
            q("Tipo evento", "Tipo evento", ["Festa privata", "Gazebo", "Giardino", "Evento aziendale", "Evento pubblico"]),
            m("Carichi", "Carichi", ["Luci", "Audio", "Frigo", "Spillatore", "Macchina ghiaccio", "Banco bar", "Piccoli elettrodomestici"]),
            q("Numero prese", "Numero prese", ["1-3", "4-6", "7-10", "Oltre 10"]),
            powerSupply,
            q("Passaggi", "Ci sono passaggi cavi critici?", ["No", "Persone", "Auto", "Non so"]),
            q("Servizio", "Servizio", ["Preventivo kit", "Check remoto", "Installazione", "Verifica in loco/DICO"]),
          ],
        },
        dj: {
          label: "Kit DJ/audio/luci",
          outcome: "Kit audio/luci",
          questions: [m("Carichi", "Carichi", ["Console DJ", "Mixer", "Casse", "Subwoofer", "Luci palco", "Macchina fumo", "Schermi/video"]), q("Linee separate", "Linee separate audio/luci?", ["Sì", "No", "Non so"]), powerSupply, uploads("Lista apparecchi, foto area, presa/quadro.")],
        },
        banco_bar: {
          label: "Kit banco bar/frigo/spillatore",
          outcome: "Kit banco bar",
          questions: [m("Carichi", "Carichi", ["Frigo", "Congelatore", "Spillatore", "Macchina ghiaccio", "Banco bar", "Macchina caffè", "Luci banco"]), q("Uso", "Uso privato o pubblico?", ["Privato", "Pubblico", "Non so"]), q("Continuità frigo", "Serve continuità frigo?", ["Sì", "No", "Non so"])],
        },
        wifi_kit: {
          label: "Kit Wi-Fi/rete dati",
          outcome: "Kit Wi-Fi",
          questions: [q("Tipo kit", "Tipo kit", ["Wi-Fi casa", "Wi-Fi B&B", "Wi-Fi negozio", "Access point esterno", "Rete ospiti", "Telecamere + rete"]), areaSize, q("Piani", "Piani", ["1", "2", "3", "Oltre 3"]), q("Dispositivi", "Dispositivi", ["1-10", "10-30", "30-60", "Oltre 60"]), uploads("Planimetria, modem/router, zone senza segnale.")],
        },
        smart_kit: {
          label: "Kit smart home/domotica",
          outcome: "Kit smart home",
          questions: [q("Tipo kit", "Tipo kit", ["Luci smart", "Tapparelle smart", "Sensori", "Controllo consumi", "Home Assistant base", "B&B smart"]), t("Numero dispositivi", "Numero dispositivi", "Es. 6 luci, 4 tapparelle"), q("Neutro scatole", "Neutro nelle scatole?", ["Sì", "No", "Non so"]), q("Servizio", "Servizio", ["Kit preconfigurato", "Assistenza remota", "Installazione", "Progetto smart home"])],
        },
        video_kit: {
          label: "Kit videosorveglianza/videocitofono",
          outcome: "Kit video",
          questions: [q("Tipo kit", "Tipo kit", ["Telecamere Wi-Fi", "PoE", "Videocitofono smart", "Controllo accessi base"]), q("Numero telecamere", "Numero telecamere", ["1-2", "3-4", "5-8", "Oltre 8"]), m("Zone", "Zone", ["Interno", "Esterno", "Ingresso", "Cancello", "Parcheggio", "Altro"]), q("Registrazione", "Registrazione", ["Cloud", "NVR locale", "Solo live", "Non so"]), uploads("Zone, modem/router, quadro, posto esterno/interno.")],
        },
        consumi_kit: {
          label: "Kit controllo consumi",
          outcome: "Kit monitoraggio",
          questions: [q("Tipo kit", "Tipo kit", ["Misuratore energia generale", "Monitoraggio singole linee", "FV + consumi", "Home Assistant energia"]), powerSupply, m("Linee da monitorare", "Linee da monitorare", ["Generale", "Cucina", "Clima", "Wallbox", "Fotovoltaico", "Pompa", "Altro"]), q("Report consumi", "Vuoi report consumi?", ["Sì", "No", "Non so"])],
        },
        emergenza_kit: {
          label: "Kit emergenza/manutenzione",
          outcome: "Kit emergenza",
          questions: [q("Tipo kit", "Tipo kit", ["Emergenza casa", "Pompa/allagamento", "Luci emergenza", "UPS piccolo ufficio", "Etichette/checklist quadro"]), t("Cosa proteggere", "Cosa vuoi proteggere?", "Es. frigo, router, pompa..."), q("Ambiente", "Ambiente", ["Casa", "Ufficio", "Garage", "Cantina", "Esterno"])],
        },
        personalizzato_kit: {
          label: "Kit personalizzato su richiesta",
          outcome: "Kit personalizzato",
          questions: [a("Esigenza", "Descrivi l'esigenza"), q("Categoria uso", "Categoria uso", ["Evento", "Casa", "B&B", "Negozio", "Ufficio", "Cantiere", "Esterno", "Altro"]), a("Carichi dispositivi", "Carichi o dispositivi da alimentare/configurare"), m("Vincoli", "Vincoli", ["Spedizione", "Ritiro", "Check remoto", "Installazione", "Documentazione", "DICO"]), uploads("Foto, planimetria, lista materiali, dati tecnici.")],
        },
      },
    },
    consiglio: {
      label: "Non so / voglio un consiglio",
      body: "Non sai da dove partire: raccogliamo pochi dati e ti richiamiamo.",
      subcategories: {
        consiglio: {
          label: "Voglio essere consigliato",
          outcome: "Richiamata e smistamento interno",
          questions: [
            a("Descrizione", "Descrivi problema o obiettivo", "Scrivi liberamente cosa vorresti fare o capire..."),
            commonWhere,
            q("Urgenza", "È urgente?", ["Sì", "No", "Non so"]),
            q("Preferenza", "Come preferisci procedere?", ["Richiamata", "Consulenza online", "Preventivo", "Sopralluogo", "Non so"]),
            uploads("Foto quadro, problema, locale, documento/preventivo o altro."),
          ],
        },
      },
    },
  };

  const categoryOrder = [
    "nuova_installazione",
    "assistenza",
    "modifica",
    "verifica",
    "consulenza",
    "kit",
    "consiglio",
  ];

  branches.nuova_installazione.subcategories.wallbox = {
    label: "Installazione wallbox",
    questions: [
      q("Parcheggio", "Dove ricaricherai l'auto?", ["Garage privato", "Posto auto esterno", "Parcheggio condominiale", "Parcheggio aziendale"]),
      powerSupply,
      q("Fotovoltaico", "Hai un impianto fotovoltaico?", ["Sì", "No", "È in progetto"]),
      q("Dispositivo", "Hai già scelto la wallbox?", ["Da scegliere insieme", "Scelta, ma da acquistare", "Già acquistata"]),
      t("Veicolo", "Quale auto vuoi ricaricare?", "Marca e modello, se già noti"),
      q("Tempistiche", "Quando vorresti installarla?", ["Appena possibile", "Entro un mese", "Entro tre mesi", "Sto valutando"]),
      uploads("Se disponibili: foto del parcheggio, del quadro elettrico e della distanza tra i due."),
    ],
  };
  branches.assistenza.subcategories.wallbox_assistenza = {
    label: "Assistenza wallbox",
    questions: [
      q("Problema", "Che problema riscontri?", ["La ricarica non parte", "Ricarica lenta o interrotta", "Scatta una protezione", "App o connessione", "Altro"]),
      t("Modello", "Qual è la wallbox?", "Marca e modello, se li conosci"),
      commonWhere,
      commonUrgency,
      uploads("Se disponibili: foto della wallbox e del messaggio di errore. Non aprire quadri o dispositivi."),
    ],
  };

  const intents = {
    nuova_installazione: { label: "Installare un nuovo impianto", icon: "plus", body: "Progetto e realizzazione da zero" },
    assistenza: { label: "Risolvere un problema", icon: "wrench", body: "Guasti, anomalie e assistenza" },
    modifica: { label: "Migliorare un impianto esistente", icon: "sliders-horizontal", body: "Aggiunte, modifiche e ampliamenti" },
    verifica: { label: "Verifiche e documentazione", icon: "clipboard-check", body: "Controlli, manutenzione e documenti" },
    consulenza: { label: "Valutare un progetto", icon: "messages-square", body: "Consulenza e secondo parere" },
    kit: { label: "Preparare una soluzione su misura", icon: "package", body: "Kit e configurazioni dedicate" },
    consiglio: { label: "Ricevere un consiglio", icon: "messages-square", body: "Raccontaci la tua esigenza" },
  };
  const services = {
    elettrico: { label: "Impianto elettrico", icon: "plug-zap", body: "Casa, attività, quadri e illuminazione", routes: {
      nuova_installazione: ["elettrico_casa", "attivita", "quadro_nuovo"],
      assistenza: ["impianto", "quadro_salvavita", "prese_luci"],
      modifica: ["prese", "punti_luce", "linea_dedicata", "quadro_modifica"],
      verifica: ["controllo_sicurezza", "manutenzione", "dico", "vendita_affitto", "report"],
      consulenza: ["secondo_parere", "analisi_preventivo", "check_dico", "ristrutturazione"],
      kit: ["consumi_kit", "emergenza_kit"],
    } },
    fotovoltaico: { label: "Fotovoltaico e accumulo", icon: "sun", body: "Produzione, batterie e consumi", routes: {
      nuova_installazione: ["fotovoltaico"], assistenza: ["fv_assistenza"], consulenza: ["fv_consulenza"],
    } },
    wallbox: { label: "Ricarica auto", icon: "ev-charger", body: "Wallbox private e aziendali", routes: {
      nuova_installazione: ["wallbox"], assistenza: ["wallbox_assistenza"],
    } },
    sicurezza: { label: "Sicurezza e videocitofoni", icon: "shield-check", body: "Telecamere, accessi e videocitofonia", routes: {
      nuova_installazione: ["videosorveglianza", "videocitofono"],
      assistenza: ["videosorveglianza_assistenza", "videocitofono_assistenza"], kit: ["video_kit"],
    } },
    rete: { label: "Wi-Fi e reti dati", icon: "wifi", body: "Copertura, connessioni e cablaggi", routes: {
      nuova_installazione: ["rete_wifi"], assistenza: ["wifi_assistenza"], modifica: ["rete_modifica"],
      consulenza: ["wifi_consulenza"], kit: ["wifi_kit"],
    } },
    domotica: { label: "Domotica", icon: "house", body: "Luci, comandi e automazioni smart", routes: {
      nuova_installazione: ["smart_home"], assistenza: ["smart_assistenza"], modifica: ["smart_modifica"],
      consulenza: ["smart_consulenza"], kit: ["smart_kit"],
    } },
    eventi: { label: "Eventi e impianti temporanei", icon: "calendar-days", body: "Stand, gazebo, palchi e allestimenti", routes: {
      nuova_installazione: ["gazebo_evento"], consulenza: ["evento_consulenza"],
      kit: ["stand", "gazebo_kit", "dj", "banco_bar", "personalizzato_kit"],
    } },
    consiglio: { label: "Altro / non so da dove partire", icon: "messages-square", body: "Descrivi liberamente ciò che ti serve", routes: { consiglio: ["consiglio"] } },
  };

  window.EletwaveQuoteData = { branches, categoryOrder, services, intents };
})();
